# Generated by Django 5.0.3 on 2025-05-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='announcements/')),
                ('datetime_add', models.DateTimeField(auto_now_add=True, verbose_name=' add date')),
                ('datetime_edit', models.DateTimeField(auto_now=True, verbose_name='edite date')),
                ('status', models.BooleanField(default=True, verbose_name='status')),
            ],
        ),
    ]
